[2019-01-18T15:51Z] System YAML configuration: /cram-bam/NA12878_37/call_cram/work/bcbio_system-merged.yaml
[2019-01-18T15:51Z] Resource requests: sambamba, samtools; memory: 3.00, 3.00; cores: 4, 4
[2019-01-18T15:51Z] Configuring 1 jobs to run, using 1 cores each with 3.00g of memory reserved for each job
[2019-01-18T15:51Z] Timing: organize samples
[2019-01-18T15:51Z] multiprocessing: organize_samples
[2019-01-18T15:51Z] Using input YAML configuration: /cram-bam/NA12878_37/call_cram/config/call_cram.yaml
[2019-01-18T15:51Z] Checking sample YAML configuration: /cram-bam/NA12878_37/call_cram/config/call_cram.yaml
[2019-01-18T15:51Z] Testing minimum versions of installed programs
[2019-01-18T15:51Z] Timing: alignment preparation
[2019-01-18T15:51Z] multiprocessing: prep_align_inputs
[2019-01-18T15:51Z] multiprocessing: disambiguate_split
[2019-01-18T15:51Z] Timing: alignment
[2019-01-18T15:51Z] multiprocessing: process_alignment
[2019-01-18T15:51Z] Create empty RG header: RMNISTHS_30xdownsample
[2019-01-18T15:51Z] Fix read groups: RMNISTHS_30xdownsample
[2019-01-18T15:51Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 86, in _do_run
    line = s.stdout.readline()
KeyboardInterrupt
